// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDFx_b86Mp7Y2LS4GNxXVPRPnOgOSri7M',
    appId: '1:312834650170:web:f0561e5273eecf54f18503',
    messagingSenderId: '312834650170',
    projectId: 'my-uni-0000',
    authDomain: 'my-uni-0000.firebaseapp.com',
    databaseURL: 'https://my-uni-0000-default-rtdb.firebaseio.com',
    storageBucket: 'my-uni-0000.appspot.com',
    measurementId: 'G-FQCK2M30MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbqYJR76l4wxzVt9vV64Mx8JerBM68dg',
    appId: '1:312834650170:android:878994eeb9f533bdf18503',
    messagingSenderId: '312834650170',
    projectId: 'my-uni-0000',
    databaseURL: 'https://my-uni-0000-default-rtdb.firebaseio.com',
    storageBucket: 'my-uni-0000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7cygHpqqxG_HJH6O5ngX5BE-r78QU7wQ',
    appId: '1:312834650170:ios:2f82f35917d1a02ff18503',
    messagingSenderId: '312834650170',
    projectId: 'my-uni-0000',
    databaseURL: 'https://my-uni-0000-default-rtdb.firebaseio.com',
    storageBucket: 'my-uni-0000.appspot.com',
    iosBundleId: 'com.example.uni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7cygHpqqxG_HJH6O5ngX5BE-r78QU7wQ',
    appId: '1:312834650170:ios:2f82f35917d1a02ff18503',
    messagingSenderId: '312834650170',
    projectId: 'my-uni-0000',
    databaseURL: 'https://my-uni-0000-default-rtdb.firebaseio.com',
    storageBucket: 'my-uni-0000.appspot.com',
    iosBundleId: 'com.example.uni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDFx_b86Mp7Y2LS4GNxXVPRPnOgOSri7M',
    appId: '1:312834650170:web:1eebbe096923e274f18503',
    messagingSenderId: '312834650170',
    projectId: 'my-uni-0000',
    authDomain: 'my-uni-0000.firebaseapp.com',
    databaseURL: 'https://my-uni-0000-default-rtdb.firebaseio.com',
    storageBucket: 'my-uni-0000.appspot.com',
    measurementId: 'G-6F88QY6C2W',
  );
}
